### ISSUE TITLE
Pytest

### ISSUE THREAD

**Issue by jssuzanne** [AnyBlok/Anyblok_Pyramid#15]
Refactored the Unittest to use pytest. I should wait the pytest branch of anyblok is merged

**Comment by petrus-v** [comment]
what will be the plan regarding provided test case class provide here : https://github.com/AnyBlok/Anyblok_Pyramid/blob/master/anyblok_pyramid/tests/testcase.py ?

I guess some new pytest feature will be provide to use in package that use this project as dependency ? and keep it for a while with a deprecated warning while migrating existing code ?

**Comment by jssuzanne** [comment]
The testcases are keeped and a deprecated warning is used

**Comment by jssuzanne** [comment]
See MR #16
