### ISSUE TITLE
Trouble with gunicorn

### ISSUE THREAD

**Issue by AlexTorx** [AnyBlok/Anyblok_Pyramid#24]
**Context** : 

We use gunicorn as provided within anyblok_pyramid as a production environment and use pyramid as provided within anyblok_pyramid for development purpose.

While everything worked fine on development server, when we deployed hence migrating our project from builtin pyramid to gunicorn, we figured out that a few features turned out not working as well as they were in our development environment.

**Trouble** : 

After some investigation, we pointed out that the impacted features were SQLAlchemy ORM events such as ***before_insert_orm_event*** method, that were not executed at all when using gunicorn compared to simple pyramid.

**Question** : 

Could this issue be related to gunicorn implementation within anyblok_pyramid or some specific configuration needed to make gunicorn work ?

**Comment by AlexTorx** [comment]
After a few hours investigating into AnyBlok core functions, I figured out that the ***listen_sqlalchemy_known_event*** method from [AnyBlok/AnyBlok/registry.py:512](https://github.com/AnyBlok/AnyBlok/blob/dfdc0b02295bb2ace900cfb6540286323021a92e/anyblok/registry.py#L512) was never called when using gunicorn, although it is when using simple pyramid with anyblok_pyramid. This function is aimed at registering sqlalchemy event listeners. Indeed, if they are not being registered at any points, they cannot be called at any moment during server runtime, which causes my exception.

This seems to happen because the ***loadwithoutmigration*** attribute from AnyBlok's registry (given at registry initialization) is set to **True** when using gunicorn, although it is set to **False** when using pyramid. Thus, the ***apply_model_schema_on_table*** method from [AnyBlok/AnyBlok/registry.py:997](https://github.com/AnyBlok/AnyBlok/blob/dfdc0b02295bb2ace900cfb6540286323021a92e/anyblok/registry.py#L997) returns instantly (when the ***loadwithoutmigration*** parameter is set to **True**) and does not execute the ***listen_sqlalchemy_known_event*** as mentioned below.

When having a look a AnyBlok Pyramid, you can figure out that the previously mentioned ***loadwithoutmigration*** parameter is used in the two functions from [AnyBlok:AnyBlok_Pyramid:common.py](https://github.com/AnyBlok/Anyblok_Pyramid/blob/300f3cee076a7678ad2e49f734b030decd5404a3/anyblok_pyramid/common.py) and defaults to **True**. Indeed when calling the ***preload_databases*** method, you can notice that when using simple pyramid, the ***loadwithoutmigration*** parameter is set to False ([here](https://github.com/AnyBlok/Anyblok_Pyramid/blob/3c75582326295b65c69693ce042d01b35e947a33/anyblok_pyramid/scripts.py#L40)) hence loading sqlalchemy events listeners, whereas when using gunicorn, calling ***preload_databases*** method ([here](https://github.com/AnyBlok/Anyblok_Pyramid/blob/80379a6b47afaee413e444f6b11923fc410b4e0d/anyblok_pyramid/gunicorn.py#L100)) is performed with default parameter (which is set to ***True***) and hence does not load sqlalchemy event listeners.

Do I miss something and is this intended or is it a mistake on gunicorn configuration ([here](https://github.com/AnyBlok/Anyblok_Pyramid/blob/80379a6b47afaee413e444f6b11923fc410b4e0d/anyblok_pyramid/gunicorn.py#L100)) ?

If this behaviour is intented, is there a way to execute the preload_databases method with the ***loadwithoutmigration*** parameter set to **True** before executing gunicorn then ?

**Comment by AlexTorx** [comment]
This is issue turned out being related to anyblok registry loading process. Loading process was rearranged in https://github.com/AnyBlok/AnyBlok/pull/138 what solved the issue.
Closing as it has been solved.

**Comment by jssuzanne** [comment]
need you a pre-release ?

**Comment by AlexTorx** [comment]
> need you a pre-release ?

In fact nothing was added to Anyblok_Pyramid since the bug was on AnyBlok core registry loading methods. Thus a pre-release on Anyblok_Pyramid is not needed. Besides, one on AnyBlok core may be cool !
